version: '3.9'
networks:
  catalog:
    external: true

services:
  envoy:
    networks:
      - catalog
    image: envoyproxy/envoy-dev:51b4927d215df821bff04d35969eb54cd53d3b31
    ports:
      - "${ENVOY_GRPC_WEB_PORT}:${ENVOY_GRPC_WEB_PORT}"
      - "${ENVOY_GRPC_PORT}:${ENVOY_GRPC_PORT}"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
