name: Deploy Catalog

on:
  workflow_dispatch:
    inputs:
      package_s3_path:
        description: 'Package s3 path. Corresponding archive should be present on pomo-packages s3 bucket'
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout action"
        uses: actions/checkout@v3

      - name: "Deploy s3"
        run: |
          set -x -e
          TEMP=$(mktemp)
          echo "${{ secrets.EC2_KEY_PAIR_CONTENTS }}" > $TEMP
          s3path=${{ inputs.package_s3_path }}
          env="Dev"
          ssh -o 'StrictHostKeyChecking no' -i $TEMP ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} \
            "bash -s" < "services/catalog/deployment/ec2/deploy.sh" "$s3path $env"