name: Deploy Catalog

on:
  workflow_call:
    inputs:
      package_s3_path:
        description: 'Package s3 path. Corresponding archive should be present on pomo-packages s3 bucket'
        required: true
        type: string
    secrets:
      EC2_KEY_PAIR_CONTENTS:
        required: true
      EC2_USERNAME:
        required: true
      EC2_HOST:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Deploy s3 22"
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY_PAIR_CONTENT
          script: whoami
      - name: "Deploy s3"
        run: |
          set -x -e
          TEMP=$(mktemp)
          echo "${{ secrets.EC2_KEY_PAIR_CONTENTS }}" > $TEMP
          s3path=${{ inputs.package_s3_path }}
          file_name=$(basename $s3path)
          ssh -o 'StrictHostKeyChecking no' -i $TEMP ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} '
            set -e -x
            rm -rf ./**
            export ENV=Dev
            aws s3 cp $s3path $file_name
            unzip $file_name
            cd "${file_name%.zip}"
            bash ./deployment/ec2/start.sh
            echo "finished from start.sh"
            echo "exiting"
            exit
          '
          echo "ssh successful"
