name: Deploy Scala app

on:
  pull_request: {}
  workflow_dispatch:
    inputs:
      env:
        description: 'ENV to deploy to'
        required: true
        options:
          - Dev
          - Prod
        type: choice
      package_s3_path:
        description: 'Package s3 path. Corresponding archive should be present on pomo-packages s3 bucket'
        required: true
        type: string
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY_PAIR_CONTENTS }}
          script: |
            set -x -e
            aws s3 copy s3://pomo-packages/4996a4f0-6f7e-4f9d-ae98-b0ec27b74fa7.zip 4996a4f0-6f7e-4f9d-ae98-b0ec27b74fa7.zip
            ls
