name: Deploy Scala app

on:
  pull_request: {}
  workflow_dispatch:
    inputs:
      env:
        description: 'ENV to deploy to'
        required: true
        options:
          - Dev
          - Prod
        type: choice
      package_s3_path:
        description: 'Package s3 path. Corresponding archive should be present on pomo-packages s3 bucket'
        required: true
        type: string
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Deploy s3"
        run: |
          set -x -e
          TEMP=$(mktemp)
          echo "${{ secrets.EC2_KEY_PAIR_CONTENTS }}" > $TEMP
          echo '
            aws s3 copy s3://pomo-packages/4996a4f0-6f7e-4f9d-ae98-b0ec27b74fa7.zip 4996a4f0-6f7e-4f9d-ae98-b0ec27b74fa7.zip
            ls -a
          ' > deploy.sh
          ssh -o 'StrictHostKeyChecking no' -i $TEMP ${{ secrets.EC2_HOST }}@${{ secrets.EC2_USERNAME }} 'bash -s' < deploy.sh

