name: "Deploy dev comment trigger"
on:
  pull_request:
    types: [opened]
  issue_comment:
    types: [created]
jobs:
  deploy-dev:
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - name: "Check dev deploy"
        id: check_dev_deploy
        uses: khan/pull-request-comment-trigger@v1.1.0
        with:
          trigger: '@deploy_dev'
          reaction: rocket
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

      - name: "Deploy to Dev"
        if: steps.check_dev_deploy.outputs.triggered == 'true'
        run: |
          echo "deploying to dev. ${{steps.check_dev_deploy.outputs.comment_body}}"
