name: Scala

on:
  pull_request: {}
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      env:
        description: 'ENV to deploy to'
        required: true
        options:
          - Dev
          - Prod
        type: choice
      commit-sha:
        description: 'Commit Sha To Deploy'
        required: false
        default: $GITHUB_SHA
        type: string

defaults:
  run:
    shell: bash
    working-directory: services/catalog

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.2
      - uses: olafurpg/setup-scala@v11
        with:
          java-version: adopt@1.11
      - name: "Starting up Postgres & Redis 🐳"
        run: |
          echo "Running catalog"
          docker network create catalog
          make local.postgres.start

      - name: Tests
        run: |
          source .env.local
          sbt -J-Xms4G -J-Xmx4G test

      - name: "Shutting down Postgres"
        run: |
          make local.postgres.stop

      - name: "Creating distribution"
        run: |
          echo "{{github.event_name}}"
