name: Scala

on:
  pull_request: {}
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      env:
        description: 'ENV to deploy to'
        required: true
        options:
          - Dev
          - Prod
        type: choice
      commit-sha:
        description: 'Commit Sha To Deploy'
        required: false
        default: $GITHUB_SHA
        type: string

defaults:
  run:
    shell: bash
    working-directory: services/catalog

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2.3.2
      - uses: olafurpg/setup-scala@v11
        with:
          java-version: adopt@1.11
      - name: "Starting up Postgres"
        run: |
          set -x -e
          echo "Running catalog"
          docker network create catalog
          make local.postgres.start

      - name: Tests
        run: |
          set -x -e
          source .env.local
          sbt -J-Xms4G -J-Xmx4G test

      - name: "Shutting down Postgres"
        run: |
          set -x -e
          make local.postgres.stop

      - name: "Creating distribution package"
        run: |
          set -x -e
          sbt -J-Xms4G -J-Xmx4G dist
          package_file_name=$(ls target/universal | grep "zip")
          package_file_path="target/universal/$package_file_name"
          export PACKAGE_FILE_PATH=$package_file_path
          echo "::set-env name=PACKAGE_FILE_PATH::$PACKAGE_FILE_PATH"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-session-name: BuildPipeline
          role-to-assume: arn:aws:iam::614277821933:role/PomoGithubWorkflows
          aws-region: eu-central-1

      - name: "Copy distribution to s3"
        run: |
          set -x -e
          if [ -z "$PACKAGE_FILE_PATH" ]
          then
            echo "PACKAGE_FILE_PATH var is not set."
            exit 1
          fi
          aws s3 cp $PACKAGE_FILE_PATH "s3://pomo-packages/$(basename "$PACKAGE_FILE_PATH")"