name: Deploy Catalog

on:
  workflow_dispatch:
    inputs:
      package_s3_path:
        description: 'Package s3 path. Corresponding archive should be present on pomo-packages s3 bucket'
        required: true
        type: string

jobs:
  deploy:
    env:
      EC2_KEY_PAIR_CONTENTS: ${{ secrets.EC2_KEY_PAIR_CONTENTS }}
      EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
      EC2_HOST: ${{ secrets.EC2_HOST }}
      S3_PATH: ${{ github.event.inputs.package_s3_path }}
      ENV: Dev
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout action"
        uses: actions/checkout@v3

      - name: "Deploy s3"
        run: .github/workflows